services:
  cder-graphrag:
    build: .
    container_name: cder-graphrag
    volumes:
      # Mount project directory
      - .:/app
      # Persist vector database
      - ./artifacts/vector_store:/app/artifacts/vector_store
      # Persist other artifacts
      - ./artifacts:/app/artifacts
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
      - 8.8.4.4
    stdin_open: true
    tty: true
    command: /bin/bash

  frontend:
    build: .
    container_name: cder-frontend
    volumes:
      - .:/app
      - ./artifacts/vector_store:/app/artifacts/vector_store
      - ./artifacts:/app/artifacts
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
    command: chainlit run frontend/app.py --port 8000 --host 0.0.0.0

